<?php
/*
* Generated By Orbisius Child Theme Creator - your favorite plugin for Child Theme creation :)
* https://wordpress.org/plugins/orbisius-child-theme-creator/
*
* Unlike style.css, the functions.php of a child theme does not override its counterpart from the parent.
* Instead, it is loaded in addition to the parent’s functions.php. (Specifically, it is loaded right before the parent theme's functions.php).
* Source: https://codex.wordpress.org/Child_Themes#Using_functions.php
*
* Be sure not to define functions, that already exist in the parent theme!
* A common pattern is to prefix function names with the (child) theme name.
* Also if the parent theme supports pluggable functions you can use function_exists( 'put_the_function_name_here' ) checks.
*/

function pd_fashion_add_woocommerce_support() {
    add_theme_support( 'woocommerce' );
}
add_action( 'after_setup_theme', 'pd_fashion_add_woocommerce_support' );
/**
 * Loads parent and child themes' style.css
 */
function pd_fashion_enqueue() {
    $parent_style = 'fashion_style';
    $parent_base_dir = 'fashionist';
    $time = time();
    if( is_product() ){
        // wp_deregister_script('jquery');
        // wp_deregister_script('jquery-migrate');
    }

    wp_enqueue_style( $parent_style,
        get_template_directory_uri() . '/style.css',
        array(),
        $time
    );

    wp_enqueue_style( 
        'font-awesome-5', 
        'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css', 
        array(), 
        '5.3.0' 
    );

    wp_enqueue_style( 'child_theme_style',
        get_stylesheet_directory_uri() . '/style.css',
        array( $parent_style ),
        $time
    );
    
    wp_enqueue_script( 'fashionist-child', get_stylesheet_directory_uri() . '/assets/js/scripts.js' , array(), $time , true);
}
add_action( 'wp_enqueue_scripts', 'pd_fashion_enqueue' );



remove_action( 'woocommerce_before_single_product_summary', 'woocommerce_show_product_images', 20 ); 
add_action( 'woocommerce_before_single_product_summary', 'fashion_woocommerce_show_product_images', 20 ); 
function fashion_woocommerce_show_product_images(){
    global $product;
    echo '<a href="'.wp_get_attachment_image_url( $product->get_image_id(), 'single-post-thumbnail' ).'">'.wp_get_attachment_image( $product->get_image_id(), 'single-post-thumbnail' ).'</a>';
}

require_once( get_stylesheet_directory() . '/inc/option-fields.php' );
require_once( get_stylesheet_directory() . '/inc/shortcodes.php' );

/**
 * Remove product data tabs
 */
add_filter( 'woocommerce_product_tabs', 'woo_remove_product_tabs', 98 );

function woo_remove_product_tabs( $tabs ) {

    // unset( $tabs['description'] );          // Remove the description tab
    unset( $tabs['reviews'] );          // Remove the reviews tab
    unset( $tabs['additional_information'] );   // Remove the additional information tab

    return $tabs;
}


add_action( 'woocommerce_after_single_product_summary', 'comments_template', 50 );

/**
 * Change Product Price Programatically
 */
add_filter('woocommerce_add_cart_item_data','wdm_add_item_data',1,10);
function wdm_add_item_data($cart_item_data, $product_id) {

    global $woocommerce;
    $product = wc_get_product( $product_id );
    if ( ! $product || ! $product->is_type( 'yith_bundle' ) ) {
        return $cart_item_data;
    }
    $new_value = array();
    if( isset($_REQUEST['green-custom-product-price']) && $_REQUEST['green-custom-product-price'] > 0 ){
        $new_value['_custom_options']['custom_price'] = $_REQUEST['green-custom-product-price'];   
    }

    if(empty($cart_item_data)) {
        return $new_value;
    } else {
        return array_merge($cart_item_data, $new_value);
    }
}
add_filter('woocommerce_get_cart_item_from_session', 'wdm_get_cart_items_from_session', 1, 3 );
function wdm_get_cart_items_from_session($item,$values,$key) {

    if (array_key_exists( '_custom_options', $values ) ) {
        $item['_custom_options'] = $values['_custom_options'];
    }

    return $item;
}

add_action( 'woocommerce_before_calculate_totals', 'update_custom_price', 1, 1 );
function update_custom_price( $cart_object ) {
    
    if ( is_admin() && ! defined( 'DOING_AJAX' ) )
        return;

    if ( did_action( 'woocommerce_before_calculate_totals' ) >= 2 )
        return;
        
    foreach ( $cart_object->cart_contents as $cart_item_key => $value ) {  
        // Version 2.x
        //$value['data']->price = $value['_custom_options']['custom_price'];
        // Version 3.x / 4.x
        if( array_key_exists('_custom_options', $value) ){
            $value['data']->set_price($value['_custom_options']['custom_price']);
        }
    }
}


/**
* @snippet       Display FREE if Price Zero or Empty - WooCommerce Single Product
* @how-to        Get CustomizeWoo.com FREE
* @author        Rodolfo Melogli
* @testedwith    WooCommerce 3.8
* @donate $9     https://businessbloomer.com/bloomer-armada/
*/
  
add_filter( 'woocommerce_get_price_html', 'bbloomer_price_free_zero_empty', 9999, 2 );
   
function bbloomer_price_free_zero_empty( $price, $product ){
    if ( '' === $product->get_price() || 0 == $product->get_price() ) {
        $price = '<span class="woocommerce-Price-amount amount">$0.00</span>';
    }  
    return $price;
}

